variable "rg_name" {}
variable "location" {}
variable "vpc_name" {}
variable "vpc_cidr_block" {}
variable "dns1" {}
variable "dns2" {}
variable "environment" {}
variable "subnet1_name" {}
variable "subnet2_name" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
